import type { BattleMapId, TilesetId } from "../../shared/ids";
import type { BattleMapDefinition, BattleTileset } from "../../core/index";

/**
 * Battle-map tilesets for the Emberwatch pack. Colors are presentation data;
 * the renderer paints them, the core only reads `blocked`.
 */
export const EMBERWATCH_TILESETS: Record<TilesetId, BattleTileset> = {
  ts_streets: {
    id: "ts_streets",
    label: "Ruined streets",
    background: "#15120e",
    kinds: {
      floor: { fill: "#4a443c" },
      floor_alt: { fill: "#403a33" },
      road: { fill: "#565046" },
      plank: { fill: "#6a5b42" },
      wall: { fill: "#2a241d", blocked: true, raised: 0.9 },
      rubble: { fill: "#57504a", blocked: true, raised: 0.3 },
      cart: { fill: "#6b502f", blocked: true, raised: 0.45 },
      water: { fill: "#23404e", blocked: true, accent: "#3d6478" },
    },
  },
  ts_docks: {
    id: "ts_docks",
    label: "Drowned docks",
    background: "#101820",
    kinds: {
      floor: { fill: "#56503f" },
      floor_alt: { fill: "#4a4436" },
      plank: { fill: "#6a5b42" },
      road: { fill: "#5a523f" },
      wall: { fill: "#27221b", blocked: true, raised: 0.9 },
      crate: { fill: "#71562f", blocked: true, raised: 0.45 },
      pillar: { fill: "#3a3a44", blocked: true, raised: 1.1 },
      water: { fill: "#1e3d4d", blocked: true, accent: "#356378" },
    },
  },
  ts_spire: {
    id: "ts_spire",
    label: "Bell Spire interior",
    background: "#0e0e16",
    kinds: {
      floor: { fill: "#444252" },
      floor_alt: { fill: "#3a3848" },
      road: { fill: "#4e4c5c" },
      wall: { fill: "#23222e", blocked: true, raised: 0.95 },
      pillar: { fill: "#56546a", blocked: true, raised: 1.2 },
    },
  },
  ts_vaults: {
    id: "ts_vaults",
    label: "Ember Vaults catacombs",
    background: "#0d0a08",
    kinds: {
      floor: { fill: "#3e3630" },
      floor_alt: { fill: "#352e29" },
      road: { fill: "#46403a" },
      wall: { fill: "#1f1a15", blocked: true, raised: 0.9 },
      bones: { fill: "#9a8d72", blocked: true, raised: 0.25 },
      pillar: { fill: "#4a4036", blocked: true, raised: 1.15 },
      ember: { fill: "#3d1f12", blocked: true, accent: "#c96a2a" },
      chasm: { fill: "#070605", blocked: true },
    },
  },
};

const STREET_LEGEND = {
  "#": "wall",
  ".": "floor",
  ",": "floor_alt",
  _: "road",
  "=": "plank",
  o: "rubble",
  c: "cart",
  "~": "water",
};

const DOCK_LEGEND = {
  "#": "wall",
  ".": "floor",
  ",": "floor_alt",
  _: "road",
  "=": "plank",
  c: "crate",
  "+": "pillar",
  "~": "water",
};

const SPIRE_LEGEND = {
  "#": "wall",
  ".": "floor",
  ",": "floor_alt",
  _: "road",
  "+": "pillar",
};

const VAULT_LEGEND = {
  "#": "wall",
  ".": "floor",
  ",": "floor_alt",
  _: "road",
  o: "bones",
  "+": "pillar",
  "~": "ember",
  x: "chasm",
};

export const EMBERWATCH_BATTLE_MAPS: Record<BattleMapId, BattleMapDefinition> = {
  bmap_ashen_road: {
    id: "bmap_ashen_road",
    tilesetId: "ts_streets",
    width: 14,
    height: 10,
    legend: STREET_LEGEND,
    rows: [
      "##############",
      "#,...o.....,.#",
      "#............#",
      "______________",
      "______________",
      "#....c...o...#",
      "#,...........#",
      "#......o....,#",
      "#..,......,..#",
      "##############",
    ],
    partySpawns: [
      { x: 1, y: 3 },
      { x: 1, y: 4 },
      { x: 2, y: 3 },
      { x: 2, y: 4 },
    ],
  },
  bmap_watchers_bridge: {
    id: "bmap_watchers_bridge",
    tilesetId: "ts_streets",
    width: 14,
    height: 10,
    legend: STREET_LEGEND,
    rows: [
      "~~~~~~~~~~~~~~",
      "~~~~~~~~~~~~~~",
      "==============",
      "......~.......",
      ".....c........",
      ".........~....",
      "==============",
      "~~~~~~~~~~~~~~",
      "~~~~~~~~~~~~~~",
      "~~~~~~~~~~~~~~",
    ],
    partySpawns: [
      { x: 1, y: 3 },
      { x: 1, y: 4 },
      { x: 1, y: 5 },
      { x: 2, y: 4 },
    ],
  },
  bmap_cinder_market: {
    id: "bmap_cinder_market",
    tilesetId: "ts_streets",
    width: 12,
    height: 12,
    legend: STREET_LEGEND,
    rows: [
      "############",
      "#,.........#",
      "#..c..c....#",
      "#..........#",
      "#....,,....#",
      "#..c.,,..c.#",
      "#....,,....#",
      "#..........#",
      "#..c....c..#",
      "#..........#",
      "#.........,#",
      "######__####",
    ],
    partySpawns: [
      { x: 5, y: 10 },
      { x: 6, y: 10 },
      { x: 4, y: 10 },
      { x: 7, y: 10 },
    ],
  },
  bmap_quay_docks: {
    id: "bmap_quay_docks",
    tilesetId: "ts_docks",
    width: 14,
    height: 10,
    legend: DOCK_LEGEND,
    rows: [
      "##############",
      "#..,......,..#",
      "#.....c......#",
      "~~==.........#",
      "~~==...c.....#",
      "~~==......,..#",
      "~~========...#",
      "~~~~~~~~==..,#",
      "~~~~~~~~==...#",
      "~~~~~~~~######",
    ],
    partySpawns: [
      { x: 10, y: 8 },
      { x: 11, y: 8 },
      { x: 12, y: 8 },
      { x: 12, y: 7 },
    ],
  },
  bmap_salt_warehouse: {
    id: "bmap_salt_warehouse",
    tilesetId: "ts_docks",
    width: 12,
    height: 10,
    legend: DOCK_LEGEND,
    rows: [
      "############",
      "#..........#",
      "#.cc...cc..#",
      "#..........#",
      "#.cc...cc..#",
      "#..........#",
      "#.cc...cc..#",
      "#..........#",
      "#...,..,...#",
      "#####__#####",
    ],
    partySpawns: [
      { x: 4, y: 8 },
      { x: 5, y: 8 },
      { x: 6, y: 8 },
      { x: 7, y: 8 },
    ],
  },
  bmap_sunken_chapel: {
    id: "bmap_sunken_chapel",
    tilesetId: "ts_docks",
    width: 12,
    height: 10,
    legend: DOCK_LEGEND,
    rows: [
      "############",
      "#....~~....#",
      "#.+..~~..+.#",
      "#..........#",
      "#~~......~~#",
      "#~~......~~#",
      "#.+......+.#",
      "#....,,....#",
      "#....,,....#",
      "#####__#####",
    ],
    partySpawns: [
      { x: 5, y: 8 },
      { x: 6, y: 8 },
      { x: 4, y: 8 },
      { x: 7, y: 8 },
    ],
  },
  bmap_harbor_hall: {
    id: "bmap_harbor_hall",
    tilesetId: "ts_docks",
    width: 12,
    height: 12,
    legend: DOCK_LEGEND,
    rows: [
      "############",
      "#,,,,..,,,,#",
      "#..........#",
      "#.+......+.#",
      "#..........#",
      "#..........#",
      "#.+......+.#",
      "#..........#",
      "#..........#",
      "#.+......+.#",
      "#..........#",
      "#####__#####",
    ],
    partySpawns: [
      { x: 5, y: 10 },
      { x: 6, y: 10 },
      { x: 4, y: 10 },
      { x: 7, y: 10 },
    ],
  },
  bmap_spire_hall: {
    id: "bmap_spire_hall",
    tilesetId: "ts_spire",
    width: 12,
    height: 12,
    legend: SPIRE_LEGEND,
    rows: [
      "############",
      "##........##",
      "#..+....+..#",
      "#..........#",
      "#..........#",
      "#....,,....#",
      "#....,,....#",
      "#..........#",
      "#..........#",
      "#..+....+..#",
      "##........##",
      "#####__#####",
    ],
    partySpawns: [
      { x: 5, y: 10 },
      { x: 6, y: 10 },
      { x: 4, y: 10 },
      { x: 7, y: 10 },
    ],
  },
  bmap_spire_stair: {
    id: "bmap_spire_stair",
    tilesetId: "ts_spire",
    width: 10,
    height: 12,
    legend: SPIRE_LEGEND,
    rows: [
      "##########",
      "##......##",
      "#....##..#",
      "#..,,##..#",
      "#..##....#",
      "#..##..,.#",
      "#....##..#",
      "#.,..##..#",
      "#..##....#",
      "#..##..,.#",
      "#........#",
      "####__####",
    ],
    partySpawns: [
      { x: 4, y: 10 },
      { x: 5, y: 10 },
      { x: 3, y: 10 },
      { x: 6, y: 10 },
    ],
  },
  bmap_spire_crown: {
    id: "bmap_spire_crown",
    tilesetId: "ts_spire",
    width: 10,
    height: 10,
    legend: SPIRE_LEGEND,
    rows: [
      "##########",
      "#..,..,..#",
      "#........#",
      "#...++...#",
      "#...++...#",
      "#........#",
      "#.,....,.#",
      "#........#",
      "#...,,...#",
      "####__####",
    ],
    partySpawns: [
      { x: 4, y: 8 },
      { x: 5, y: 8 },
      { x: 3, y: 7 },
      { x: 6, y: 7 },
    ],
  },
  bmap_ossuary: {
    id: "bmap_ossuary",
    tilesetId: "ts_vaults",
    width: 12,
    height: 10,
    legend: VAULT_LEGEND,
    rows: [
      "############",
      "#..o...o...#",
      "#.##.##.##.#",
      "#..........#",
      "#.##.##.##.#",
      "#..o....o..#",
      "#.##.##.##.#",
      "#..........#",
      "#....,,....#",
      "#####__#####",
    ],
    partySpawns: [
      { x: 5, y: 8 },
      { x: 6, y: 8 },
      { x: 4, y: 8 },
      { x: 7, y: 8 },
    ],
  },
  bmap_cistern: {
    id: "bmap_cistern",
    tilesetId: "ts_vaults",
    width: 12,
    height: 10,
    legend: VAULT_LEGEND,
    rows: [
      "############",
      "#..........#",
      "#..~~~~~~..#",
      "#..~~~~~~..#",
      "#..~~~~~~..#",
      "#..~~~~~~..#",
      "#..........#",
      "#.o......o.#",
      "#....,,....#",
      "#####__#####",
    ],
    partySpawns: [
      { x: 5, y: 8 },
      { x: 6, y: 8 },
      { x: 4, y: 8 },
      { x: 7, y: 8 },
    ],
  },
  bmap_deep_vault: {
    id: "bmap_deep_vault",
    tilesetId: "ts_vaults",
    width: 12,
    height: 12,
    legend: VAULT_LEGEND,
    rows: [
      "############",
      "#,,......,,#",
      "#..+....+..#",
      "#..........#",
      "#xx......xx#",
      "#xx......xx#",
      "#..........#",
      "#..+....+..#",
      "#..........#",
      "#....oo....#",
      "#..........#",
      "#####__#####",
    ],
    partySpawns: [
      { x: 5, y: 10 },
      { x: 6, y: 10 },
      { x: 4, y: 10 },
      { x: 7, y: 10 },
    ],
  },
};
